[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
version = "1.0.0"
name = "cht_utils"
authors = [
    {name = "Maarten van Ormondt", email = "maarten.vanormondt@deltares-usa.us"},
]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "shapely",
    "pandas",
    "geopandas",
    "pyproj",
    "paramiko",
    "xarray",
    "scipy",
    "pyyaml",
]
